name: Deploy Angular Project
on: 
  workflow_call:
    inputs: 
      image-full-name:
        required: true
        type: string
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
    - name: Display Environment Info
      run: |
        echo "Image Path: ${{ inputs.image-full-name }}"
        echo "Token :  ${{ secrets.TOKEN }}"
    