name: Deploy Angular Project
on: 
  workflow_call:
    inputs: 
      image-full-name:
        required: true
        type: string
jobs:
  show-info:
    runs-on: ubuntu-latest
    token: ${{ secrets.TOKEN }}
    image-path: ${{ inputs.image-full-name }}
    steps:
    - name: Display Environment Info
      run: |
        echo "Image Path: $image-path"
        echo "Token : $token"
    